name: Update Nginx Config

on: 
  push

env:
  HOST: 120.24.161.118
  USERNAME: ecs-user
  DOCKER_NAME: test

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Transfer Nginx Config File
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.ALIYUN_ECS_SSH_SECRET }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          scp -o StrictHostKeyChecking=no ./default.conf ${{ env.USERNAME }}@${{ env.HOST }}:~/default.conf
      
      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          key: ${{ secrets.ALIYUN_ECS_SSH_SECRET }}
          port: 22
          script: |
            docker cp ./default.conf ${{ env.DOCKER_NAME }}:/etc/nginx/conf.d/default.conf
            docker exec -i ${{ env.DOCKER_NAME }} nginx -s reload
